apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secrets
type: Opaque
stringData:
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_ROOT_PASSWORD: #rootpassword
  MYSQL_PASSWORD: #password
