apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
  creationTimestamp: "2024-06-26T09:29:04Z"
  labels:
    app: nextcloud
  name: nextcloud

spec:
  enableServiceLinks: false
  hostname: nextcloud
  restartPolicy: OnFailure

  containers:
    - name: maria-db
      image: docker.io/library/mariadb:latest
      args:
        - --transaction-isolation=READ-COMMITTED
        - --log-bin=binlog
        - --binlog-format=ROW
      envFrom:
        - secretRef:
            name: nextcloud-db-secrets
      volumeMounts:
        - mountPath: /var/lib/mysql/
          name: nextcloud_db

    - name: redis
      image: docker.io/library/redis:alpine
      args:
        - redis-server
        - --requirepass
        - $(REDIS_HOST_PASSWORD)
      envFrom:
        - secretRef:
            name: nextcloud-redis-secrets

    - name: nextcloud
      image: docker.io/library/nextcloud:fpm-alpine
      args:
        - php-fpm
      env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MYSQL_HOST
          value: 127.0.0.1
      envFrom:
        - secretRef:
            name: nextcloud-db-secrets
        - secretRef:
            name: nextcloud-redis-secrets
      volumeMounts:
        - mountPath: /var/www/html/
          name: nextcloud_html
        - mountPath: /var/www/html/data
          name: nextcloud_data

    - name: caddy
      image: docker.io/library/caddy:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - mountPath: /var/www/html:ro
          name: nextcloud_html
        - mountPath: /data
          name: nextcloud_caddy_data
        - mountPath: /etc/caddy
          name: nextcloud_caddy_conf

  volumes:
    - hostPath:
        path: /droppi/nextcloud/caddy/caddy_data
        type: Directory
      name: nextcloud_caddy_data
    - hostPath:
        path: /droppi/nextcloud/caddy/conf
        type: Directory
      name: nextcloud_caddy_conf
    - hostPath:
        path: /droppi/nextcloud/mariadb
        type: Directory
      name: nextcloud_db
    - hostPath:
        path: /droppi/nextcloud/html
        type: Directory
      name: nextcloud_html
    - hostPath:
        path: /droppi/nextcloud/data
        type: Directory
      name: nextcloud_data
status: {}
